---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: netpol-dashboard
  namespace: netpol-system
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: netpol-dashboard
  namespace: netpol-system
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: netpol-dashboard:latest
